//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEsig.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa_salario
    {
        public int Pessoa_ID { get; set; }
        public string Nome { get; set; }
        public decimal Salario { get; set; }
    }
}
